
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvszufnafhfiyprcvfep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2c3p1Zm5hZmhmaXlwcmN2ZmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTY0NjEsImV4cCI6MjA2NTk3MjQ2MX0.OZKkKcVGS2-UwSZJj7IogqRomIko8YdDSRjclzdV408";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
